// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWmMzgtXcx5nAVbVeH8OEkhXxPMJlPz8',
    appId: '1:218454027223:web:d6d228ec12570974de7992',
    messagingSenderId: '218454027223',
    projectId: 'social-app-5fc91',
    authDomain: 'social-app-5fc91.firebaseapp.com',
    storageBucket: 'social-app-5fc91.appspot.com',
    measurementId: 'G-B198YBRTTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpgvEFcB2iJgCqIZFCf1brnKHdU6BfFI',
    appId: '1:218454027223:android:f345177e19f6462ede7992',
    messagingSenderId: '218454027223',
    projectId: 'social-app-5fc91',
    storageBucket: 'social-app-5fc91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr2ph9e1crG8_8KxUxPIB1U6iw-eVh6Hg',
    appId: '1:218454027223:ios:769fdf6f189f42b2de7992',
    messagingSenderId: '218454027223',
    projectId: 'social-app-5fc91',
    storageBucket: 'social-app-5fc91.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr2ph9e1crG8_8KxUxPIB1U6iw-eVh6Hg',
    appId: '1:218454027223:ios:769fdf6f189f42b2de7992',
    messagingSenderId: '218454027223',
    projectId: 'social-app-5fc91',
    storageBucket: 'social-app-5fc91.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWmMzgtXcx5nAVbVeH8OEkhXxPMJlPz8',
    appId: '1:218454027223:web:68c2e40cd942416cde7992',
    messagingSenderId: '218454027223',
    projectId: 'social-app-5fc91',
    authDomain: 'social-app-5fc91.firebaseapp.com',
    storageBucket: 'social-app-5fc91.appspot.com',
    measurementId: 'G-P5F9H14R0Z',
  );
}
